/*ENCONTRE O NOME DOS FILMES DE GENERO AÇÃO E FANTASIA*/
SELECT F.NOME
FROM FILMES F
WHERE F.ID IN (
    SELECT FG.ID_FILME
    FROM FILMES_GENEROS FG
    WHERE FG.ID_GENERO IN (
        SELECT G.ID
        FROM GENEROS G
        WHERE G.NOME IN ('Ação', 'Fantasia')
    )
);

/*ENCONTRE O NOME DOS USUARIO QUE QUEREM LER HARRY POTTER E A PEDRA FILOSOFAL*/
SELECT U.NOME
FROM USUARIOS U
WHERE U.USUARIO IN (
    SELECT UL.USUARIO
    FROM USUARIO UL
    WHERE UL.ID_LIVRO IN (
        SELECT L.ID
        FROM LIVROS L
        WHERE L.TITULO = 'Harry Potter e a pedra filosofal' AND L.STATUS = 'Quero ler'
    )
);

/*ENCONTRE O NOME DOS LIVROS ESCRITOS POR JK ROWLING*/
SELECT L.TITULO
FROM LIVROS L
WHERE L.ID IN (
    SELECT LE.ID_LIVRO
    FROM LIVRO_ESCRITO_POR LE
    WHERE LE.ID_AUTOR IN (
        SELECT A.ID
        FROM AUTORES A
        WHERE A.NOME = 'J.K. Rowling'
    )
);

/*ENCONTRE O NOME DOS AUTORES QUE ESCREVERAM LIVROS DE GENERO FANTASIA*/
SELECT A.NOME
FROM AUTORES A
WHERE A.ID IN (
    SELECT LE.ID_AUTOR
    FROM LIVRO_ESCRITO_POR LE
    WHERE LE.ID_LIVRO IN (
        SELECT LG.ID_LIVRO
        FROM LIVRO_GENERO LG
        WHERE LG.ID IN (
            SELECT G.ID
            FROM GENEROS G
            WHERE G.NOME = 'Fantasia'
        )
    )
);

/*ENCONTRE O NOME DOS GENEROS QUE TEM MAIS DE 4 LIVROS*/
SELECT G.NOME
FROM GENEROS G
WHERE G.ID IN (
    SELECT LG.ID_GENERO
    FROM LIVRO_GENERO LG
    WHERE LG.ID_LIVRO IN (
        SELECT L.ID
        FROM LIVROS L
        GROUP BY L.ID
        HAVING COUNT(L.ID) > 4
        )
    )
);

/*ENCONTE O NOME DOS AUTORES QUE ESCREVERAM MAIS DE 7 LIVROS*/
SELECT A.NOME
FROM AUTORES A
WHERE A.ID IN (
    SELECT LE.ID_AUTOR
    FROM LIVRO_ESCRITO_POR LE
    WHERE LE.ID_LIVRO IN (
        SELECT L.ID
        FROM LIVROS L
        GROUP BY L.ID
        HAVING COUNT(L.ID) > 7
        )
    )
);

/*ENCONTRE O NOME DOS FILMES COM O ATOR DANIEL RADCLIFFE*/
SELECT F.NOME
FROM FILMES F
WHERE F.ID IN (
    SELECT FA.ID_FILME
    FROM FILME_ATORES FA
    WHERE FA.ID_ATOR IN (
        SELECT A.ID
        FROM ATORES A
        WHERE A.NOME = 'Daniel Radcliffe'
    )
);

/*ENCONTE O NOME DOS ATORES QUE GANHARAM UM OSCAR*/
SELECT A.NOME
FROM ATORES A
WHERE A.ID IN (
    SELECT P.ID_ATOR
    FROM PREMIOS P
    WHERE P.NOME = 'Oscar'
);

/*ENCONTE O NOME DOS FILMES QUE TEM MAIS DE 5 GENEROS*/
SELECT F.NOME
FROM FILMES F
WHERE F.ID IN (
    SELECT FG.ID_FILME
    FROM FILMES_GENEROS FG
    GROUP BY FG.ID_FILME
    HAVING COUNT(FG.ID_FILME) > 5
    )
);

/*ENCONTRE O NOME DOS USUARIOS QUE JA LERAM ALGUM LIVRO DE FANTASIA*/
SELECT U.USUARIO
FROM USUARIOS U
WHERE U.USUARIO IN (
    SELECT UL.USUARIO
    FROM USUARIO_ACOMPANHA_LIVROS UL
    WHERE UL.ID_LIVRO IN (
        SELECT L.ID
        FROM LIVROS L
        WHERE L.TITULO IN (
            SELECT L.TITULO
            FROM LIVROS L
            WHERE L.ID IN (
                SELECT LG.ID_LIVRO
                FROM LIVRO_GENERO LG
                WHERE LG.ID_GENERO IN (
                    SELECT G.ID
                    FROM GENEROS G
                    WHERE G.NOME = 'Fantasia'
                )
            )
        )
        
    )
)


