DROP TABLE IF EXISTS PACIENTE_INTERNADO_QUARTO;
DROP TABLE IF EXISTS MEDICO_RESPONDE_PACIENTE;
DROP TABLE IF EXISTS MEDICO_TRATA_PACIENTE;
DROP TABLE IF EXISTS MEDICO_CONTRATADO_PARA;
DROP TABLE IF EXISTS MEDICO_FORMADO_EM;

DROP TABLE IF EXISTS MEDICO;
DROP TABLE IF EXISTS ESPECIALIDADE;
DROP TABLE IF EXISTS PACIENTE;
DROP TABLE IF EXISTS QUARTO;



CREATE TABLE MEDICO (
    CRM INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    SALARIO DECIMAL(10,2) NOT NULL
);

CREATE TABLE ESPECIALIDADE (
    NOME VARCHAR(50) NOT NULL PRIMARY KEY
);

CREATE TABLE PACIENTE (
    CPF VARCHAR(11) NOT NULL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    RG VARCHAR(9) NOT NULL
);

CREATE TABLE QUARTO (
    NUMERO INTEGER NOT NULL PRIMARY KEY,
    ANDAR INTEGER NOT NULL
);

/*------------RELAÇÕES---------------*/

CREATE TABLE MEDICO_FORMADO_EM (
    CRM INTEGER,
    ESPECIALIDADE VARCHAR(50) NOT NULL,

    PRIMARY KEY (CRM, ESPECIALIDADE),
    FOREIGN KEY (CRM) REFERENCES MEDICO (CRM),
    FOREIGN KEY (ESPECIALIDADE) REFERENCES ESPECIALIDADE (NOME)
);

CREATE TABLE MEDICO_CONTRATADO_PARA (
    CRM INTEGER,
    ESPECIALIDADE VARCHAR(50) NOT NULL,

    PRIMARY KEY (CRM),
    FOREIGN KEY (CRM) REFERENCES MEDICO (CRM),
    FOREIGN KEY (ESPECIALIDADE) REFERENCES ESPECIALIDADE (NOME)
);

CREATE TABLE MEDICO_TRATA_PACIENTE (
    CRM INTEGER,
    CPF VARCHAR(11),

    PRIMARY KEY (CRM, CPF),
    FOREIGN KEY (CRM) REFERENCES MEDICO (CRM),
    FOREIGN KEY (CPF) REFERENCES PACIENTE (CPF)
);

CREATE TABLE MEDICO_RESPONDE_PACIENTE (
    CRM INTEGER NOT NULL,
    CPF VARCHAR(11),
    HORARIO VARCHAR(10),

    PRIMARY KEY (CPF),
    FOREIGN KEY (CRM) REFERENCES MEDICO (CRM),
    FOREIGN KEY (CPF) REFERENCES PACIENTE (CPF)
);

CREATE TABLE PACIENTE_INTERNADO_QUARTO (
    CPF VARCHAR(11),
    NUMERO INTEGER,

    FOREIGN KEY (CPF) REFERENCES PACIENTE (CPF),
    FOREIGN KEY (NUMERO) REFERENCES QUARTO (NUMERO)
);