DROP TABLE IF EXISTS REVENDEDOR_TEM_LOTE_EXCLUSIVO;
DROP TABLE IF EXISTS LOTE_EXCLUSIVO_TEM_NOTAS;
DROP TABLE IF EXISTS PICOLE_LEITE_TEM_LOTE_LEITE;
DROP TABLE IF EXISTS PICOLE_NORMAL_TEM_LOTE_NORMAL;
DROP TABLE IF EXISTS PICOLE_LEITE_TEM_CONSERVANTES;
DROP TABLE IF EXISTS PICOLE_NORMAL_TEM_ADITIVOS_NUTRITIVOS;
DROP TABLE IF EXISTS PICOLES_EMBALAGENS;
DROP TABLE IF EXISTS PICOLES_INGREDIENTES;
DROP TABLE IF EXISTS NOTAS;
DROP TABLE IF EXISTS REVENDEDORES;
DROP TABLE IF EXISTS LOTE_LEITE;
DROP TABLE IF EXISTS LOTE_NORMAL;
DROP TABLE IF EXISTS LOTE_EXCLUSIVO;
DROP TABLE IF EXISTS CONSERVANTES;
DROP TABLE IF EXISTS ADITIVOS_NUTRITIVOS;
DROP TABLE IF EXISTS EMBALAGENS;
DROP TABLE IF EXISTS PICOLE_LEITE;
DROP TABLE IF EXISTS PICOLE_NORMAL;
DROP TABLE IF EXISTS PICOLES;
DROP TABLE IF EXISTS INGREDIENTES;

CREATE TABLE INGREDIENTES (
    NOME VARCHAR(50) NOT NULL PRIMARY KEY
);

CREATE TABLE PICOLES (
    SABOR VARCHAR(50) NOT NULL PRIMARY KEY,
    PREÇO DECIMAL(10,2) NOT NULL
);

CREATE TABLE PICOLE_NORMAL (
    SABOR VARCHAR(50) NOT NULL,
    FOREIGN KEY (SABOR) REFERENCES PICOLES(SABOR),
    PRIMARY KEY (SABOR)
);

CREATE TABLE PICOLE_LEITE (
    SABOR VARCHAR(50) NOT NULL,
    FOREIGN KEY (SABOR) REFERENCES PICOLES(SABOR),
    PRIMARY KEY (SABOR)
);

CREATE TABLE EMBALAGENS (
    NOME VARCHAR(50) NOT NULL PRIMARY KEY
);

CREATE TABLE ADITIVOS_NUTRITIVOS (
    NOME VARCHAR(50) NOT NULL PRIMARY KEY,
    FORMULA VARCHAR(50) NOT NULL
);

CREATE TABLE CONSERVANTES (
    NOME VARCHAR(50) NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(50) NOT NULL
);

CREATE TABLE LOTE_EXCLUSIVO (
    ID INTEGER NOT NULL PRIMARY KEY
);

CREATE TABLE LOTE_NORMAL (
    ID INTEGER NOT NULL,
    FOREIGN KEY (ID) REFERENCES LOTE_EXCLUSIVO(ID),
    PRIMARY KEY (ID)
);

CREATE TABLE LOTE_LEITE (
    ID INTEGER NOT NULL,
    FOREIGN KEY (ID) REFERENCES LOTE_EXCLUSIVO(ID),
    PRIMARY KEY (ID)
);

CREATE TABLE REVENDEDORES (
    CNPJ VARCHAR(50) NOT NULL PRIMARY KEY,
    RAZÃO_SOCIAL VARCHAR(50) NOT NULL,
    CONTATO VARCHAR(50) NOT NULL
);

CREATE TABLE NOTAS (
    NUM INTEGER NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(50) NOT NULL,
    DATA DATE NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL
);





CREATE TABLE PICOLES_INGREDIENTES (
    SABOR VARCHAR(50) NOT NULL,
    INGREDIENTE VARCHAR(50) NOT NULL,

    PRIMARY KEY (INGREDIENTE),

    FOREIGN KEY (SABOR) REFERENCES PICOLES(SABOR),
    FOREIGN KEY (INGREDIENTE) REFERENCES INGREDIENTES(NOME)
);

CREATE TABLE PICOLES_EMBALAGENS (
    SABOR VARCHAR(50) NOT NULL,
    EMBALAGEM VARCHAR(50) NOT NULL,

    PRIMARY KEY (SABOR),

    FOREIGN KEY (SABOR) REFERENCES PICOLES(SABOR),
    FOREIGN KEY (EMBALAGEM) REFERENCES EMBALAGENS(NOME)
);

CREATE TABLE PICOLE_NORMAL_TEM_ADITIVOS_NUTRITIVOS (
    SABOR VARCHAR(50) NOT NULL,
    ADITIVO_NUTRITIVO VARCHAR(50) NOT NULL,

    PRIMARY KEY (SABOR, ADITIVO_NUTRITIVO),

    FOREIGN KEY (SABOR) REFERENCES PICOLE_NORMAL(SABOR),
    FOREIGN KEY (ADITIVO_NUTRITIVO) REFERENCES ADITIVOS_NUTRITIVOS(NOME)
);

CREATE TABLE PICOLE_LEITE_TEM_CONSERVANTES (
    SABOR VARCHAR(50) NOT NULL,
    CONSERVANTE VARCHAR(50) NOT NULL,

    PRIMARY KEY (SABOR, CONSERVANTE),

    FOREIGN KEY (SABOR) REFERENCES PICOLE_LEITE(SABOR),
    FOREIGN KEY (CONSERVANTE) REFERENCES CONSERVANTES(NOME)
);

CREATE TABLE PICOLE_NORMAL_TEM_LOTE_NORMAL (
    SABOR VARCHAR(50) NOT NULL,
    LOTE_NORMAL INTEGER NOT NULL,
    QTDE INTEGER NOT NULL,

    PRIMARY KEY (SABOR, LOTE_NORMAL),

    FOREIGN KEY (SABOR) REFERENCES PICOLE_NORMAL(SABOR),
    FOREIGN KEY (LOTE_NORMAL) REFERENCES LOTE_NORMAL(ID)
);

CREATE TABLE PICOLE_LEITE_TEM_LOTE_LEITE (
    SABOR VARCHAR(50) NOT NULL,
    LOTE_LEITE INTEGER NOT NULL,
    QTDE INTEGER NOT NULL,

    PRIMARY KEY (SABOR, LOTE_LEITE),

    FOREIGN KEY (SABOR) REFERENCES PICOLE_LEITE(SABOR),
    FOREIGN KEY (LOTE_LEITE) REFERENCES LOTE_LEITE(ID)
);

CREATE TABLE LOTE_EXCLUSIVO_TEM_NOTAS (
    ID INTEGER NOT NULL,
    NOTA INTEGER NOT NULL,

    PRIMARY KEY (NOTA),

    FOREIGN KEY (ID) REFERENCES LOTE_EXCLUSIVO(ID),
    FOREIGN KEY (NOTA) REFERENCES NOTAS(NUM)
);

CREATE TABLE REVENDEDOR_TEM_LOTE_EXCLUSIVO (
    CNPJ VARCHAR(50) NOT NULL,
    ID INTEGER NOT NULL,

    PRIMARY KEY (ID),

    FOREIGN KEY (CNPJ) REFERENCES REVENDEDORES(CNPJ),
    FOREIGN KEY (ID) REFERENCES LOTE_EXCLUSIVO(ID)
);