ex01:
	gcc -o ex01 ex01.c -lGL -lglut -lGLU

ex02:
	gcc -o ex02 ex02.c -lGL -lglut -lGLU

ex03:
	gcc -o ex03 ex03.c -lGL -lglut -lGLU

ex04:
	gcc -o ex04 ex04.c -lGL -lglut -lGLU

ex05:
	gcc -o ex05 ex05.c -lGL -lglut -lGLU -lm