DROP TABLE IF EXISTS TEM_ENTIDADE_C;
DROP TABLE IF EXISTS TEM_ENTIDADE_B;
DROP TABLE IF EXISTS ENTIDADE_A;

CREATE TABLE ENTIDADE_A(
    ATRIBUTO_A1 INTEGER NOT NULL,
    ATRIBUTO_A2 VARCHAR(20) NOT NULL,
    PRIMARY KEY (ATRIBUTO_A1)
);

CREATE TABLE TEM_ENTIDADE_B(
    ATRIBUTO_B1 INTEGER NOT NULL,
    ATRIBUTO_B2 VARCHAR(20) NOT NULL,
    ATRIBUTO_A1 INTEGER NOT NULL,
    PRIMARY KEY (ATRIBUTO_A1, ATRIBUTO_B1),
    FOREIGN KEY (ATRIBUTO_A1) REFERENCES ENTIDADE_A(ATRIBUTO_A1)
);

CREATE TABLE TEM_ENTIDADE_C(
    ATRIBUTO_C1 INTEGER NOT NULL,
    ATRIBUTO_C2 VARCHAR(20) NOT NULL,
    ATRIBUTO_A1 INTEGER NOT NULL,
    ATRIBUTO_B1 INTEGER NOT NULL,
    PRIMARY KEY (ATRIBUTO_A1,ATRIBUTO_B1,ATRIBUTO_C1),
    FOREIGN KEY (ATRIBUTO_A1,ATRIBUTO_B1) REFERENCES TEM_ENTIDADE_B(ATRIBUTO_A1,ATRIBUTO_B1)
);
