/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EXEMPLOXDR_H_RPCGEN
#define _EXEMPLOXDR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Person {
	char *name;
	char *place;
	u_int year;
};
typedef struct Person Person;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Person (XDR *, Person*);

#else /* K&R C */
extern bool_t xdr_Person ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EXEMPLOXDR_H_RPCGEN */
