/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "exemploxdr.h"

bool_t
xdr_Person (XDR *xdrs, Person *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->place, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->year))
		 return FALSE;
	return TRUE;
}
