// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "exemplo_cdr.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



void
Person::operator>>= (cdrStream &_n) const
{
  _n.marshalString(name,0);
  _n.marshalString(place,0);
  year >>= _n;

}

void
Person::operator<<= (cdrStream &_n)
{
  name = _n.unmarshalString(0);
  place = _n.unmarshalString(0);
  (::CORBA::ULong&)year <<= _n;

}

