// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __exemplo__cdr_hh__
#define __exemplo__cdr_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_exemplo__cdr
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_exemplo__cdr
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_exemplo__cdr
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





struct Person {
  typedef _CORBA_ConstrType_Variable_Var<Person> _var_type;

  
  ::CORBA::String_member name;

  ::CORBA::String_member place;

  ::CORBA::ULong year;



  void operator>>= (cdrStream &) const;
  void operator<<= (cdrStream &);
};

typedef Person::_var_type Person_var;

typedef _CORBA_ConstrType_Variable_OUT_arg< Person,Person_var > Person_out;









#undef _core_attr
#undef _dyn_attr





#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_exemplo__cdr
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_exemplo__cdr
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_exemplo__cdr
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_exemplo__cdr
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_exemplo__cdr
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_exemplo__cdr
#endif

#endif  // __exemplo__cdr_hh__

