
/**
* Person.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exemplo_cdr.idl
* Wednesday, April 11, 2018 9:51:41 PM BRT
*/

public final class Person implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String place = null;
  public int year = (int)0;

  public Person ()
  {
  } // ctor

  public Person (String _name, String _place, int _year)
  {
    name = _name;
    place = _place;
    year = _year;
  } // ctor

} // class Person
