use TRAB2;

DROP TABLE IF EXISTS VAGAS_CLIENTES;
DROP TABLE IF EXISTS VAGAS_ESTACIONAGEM;
DROP TABLE IF EXISTS CIENTES_ESTACIONAGEM;
DROP TABLE IF EXISTS VAGA_AVULSA;
DROP TABLE IF EXISTS VAGA_MENSAL_CLIENTE;
DROP TABLE IF EXISTS VAGA_MENSAL;
DROP TABLE IF EXISTS VAGAS;
DROP TABLE IF EXISTS ESTACIONAGEM;
DROP TABLE IF EXISTS CLIENTES;



CREATE TABLE IF NOT EXISTS VAGAS (
    ID INTEGER PRIMARY KEY NOT NULL,
    STATUS ENUM('LIVRE', 'OCUPADA') NOT NULL
);

CREATE TABLE IF NOT EXISTS VAGA_AVULSA (
    ID INTEGER,
    CUSTO_HORA_CARRO FLOAT,
    CUSTO_HORA_MOTO FLOAT,

    FOREIGN KEY (ID) REFERENCES VAGAS(ID),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS VAGA_MENSAL (
    ID INTEGER,
    CUSTO_MENSAL_CARRO FLOAT,
    CUSTO_MENSAL_MOTO FLOAT,

    FOREIGN KEY (ID) REFERENCES VAGAS(ID),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ESTACIONAGEM (
    ID INTEGER PRIMARY KEY,
    DATA_HORA_ENTRADA CHAR(5),
    DATA_HORA_SAIDA CHAR(5),
    PLACA CHAR(7),
    CUSTO FLOAT
);

CREATE TABLE IF NOT EXISTS VAGAS_ESTACIONAGEM (
    ID_VAGA INTEGER,
    ID_ESTACIONAGEM INTEGER,

    PRIMARY KEY (ID_ESTACIONAGEM),
    FOREIGN KEY (ID_VAGA) REFERENCES VAGAS(ID),
    FOREIGN KEY (ID_ESTACIONAGEM) REFERENCES ESTACIONAGEM(ID)
);

CREATE TABLE CLIENTES (
    CPF CHAR(11) PRIMARY KEY,
    NOME CHAR(50)
);

CREATE TABLE CIENTES_ESTACIONAGEM (
    CPF CHAR(11),
    ID_ESTACIONAGEM INTEGER,

    PRIMARY KEY (ID_ESTACIONAGEM),
    FOREIGN KEY (CPF) REFERENCES CLIENTES(CPF),
    FOREIGN KEY (ID_ESTACIONAGEM) REFERENCES ESTACIONAGEM(ID)
);

CREATE TABLE IF NOT EXISTS VAGA_MENSAL_CLIENTE (
    ID INTEGER,
    CPF CHAR(11),

    PRIMARY KEY (ID, CPF),
    FOREIGN KEY (ID) REFERENCES VAGA_MENSAL(ID),
    FOREIGN KEY (CPF) REFERENCES CLIENTES(CPF)
);



