DROP TABLE IF EXISTS PROFESSOR_LECIONA_TURMA;
DROP TABLE IF EXISTS INSCRICAO_TURMA;
DROP TABLE IF EXISTS PRE_REQUISITO;
DROP TABLE IF EXISTS CURSO_TEM_DICIPLINA;
DROP TABLE IF EXISTS INSCRICAO_CURSO;
DROP TABLE IF EXISTS PESSOA_FAZ_INSCRICAO;
DROP TABLE IF EXISTS FUNCIONARIO_AUXILIA_PROFESSOR;

DROP TABLE IF EXISTS TURMA;
DROP TABLE IF EXISTS DICIPLINA;
DROP TABLE IF EXISTS CURSO;
DROP TABLE IF EXISTS INSCRICAO;
DROP TABLE IF EXISTS PROFESSOR;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS ALUNO;
DROP TABLE IF EXISTS PESSOA;



CREATE TABLE PESSOA (
    ID INTEGER NOT NULL PRIMARY KEY
);

CREATE TABLE ALUNO (
    ID_PESSOA INTEGER NOT NULL,

    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA (ID),
    PRIMARY KEY (ID_PESSOA)
);

CREATE TABLE FUNCIONARIO (
    ID_PESSOA INTEGER NOT NULL,

    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA (ID),
    PRIMARY KEY (ID_PESSOA)
);

CREATE TABLE PROFESSOR (
    ID_PESSOA INTEGER NOT NULL,

    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA (ID),
    PRIMARY KEY (ID_PESSOA)
);

CREATE TABLE INSCRICAO(
    ID INTEGER NOT NULL PRIMARY KEY,
    INICIO DATE NOT NULL,
    FIM DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL
);

CREATE TABLE CURSO (
    NOME VARCHAR(50) NOT NULL PRIMARY KEY
);

CREATE TABLE DICIPLINA (
    NOME VARCHAR(50) NOT NULL PRIMARY KEY
);

CREATE TABLE TURMA (
    SEMESTRE_ANO INTEGER NOT NULL,
    NOME_CURSO VARCHAR(50) NOT NULL,
    NOME_DICIPLINA VARCHAR(50) NOT NULL,

    PRIMARY KEY (SEMESTRE_ANO, NOME_CURSO, NOME_DICIPLINA),

    FOREIGN KEY (NOME_CURSO) REFERENCES CURSO (NOME),
    FOREIGN KEY (NOME_DICIPLINA) REFERENCES DICIPLINA (NOME)


);

/*----------------relações---------------*/

CREATE TABLE FUNCIONARIO_AUXILIA_PROFESSOR (
    ID_FUNCIONARIO INTEGER NOT NULL,
    ID_PROFESSOR INTEGER NOT NULL,

    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO (ID_PESSOA),
    FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSOR (ID_PESSOA),
    PRIMARY KEY (ID_FUNCIONARIO, ID_PROFESSOR)
);

CREATE TABLE PESSOA_FAZ_INSCRICAO (
    ID_PESSOA INTEGER NOT NULL,
    ID_INSCRICAO INTEGER NOT NULL,

    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA (ID),
    FOREIGN KEY (ID_INSCRICAO) REFERENCES INSCRICAO (ID),
    PRIMARY KEY (ID_INSCRICAO)
);

CREATE TABLE INSCRICAO_CURSO (
    ID_INSCRICAO INTEGER NOT NULL,
    NOME_CURSO VARCHAR(50) NOT NULL,

    FOREIGN KEY (ID_INSCRICAO) REFERENCES INSCRICAO (ID),
    FOREIGN KEY (NOME_CURSO) REFERENCES CURSO (NOME),
    PRIMARY KEY (ID_INSCRICAO)
);

CREATE TABLE CURSO_TEM_DICIPLINA (
    NOME_CURSO VARCHAR(50) NOT NULL,
    NOME_DICIPLINA VARCHAR(50) NOT NULL,

    FOREIGN KEY (NOME_CURSO) REFERENCES CURSO (NOME),
    FOREIGN KEY (NOME_DICIPLINA) REFERENCES DICIPLINA (NOME),
    PRIMARY KEY (NOME_CURSO, NOME_DICIPLINA)
);

CREATE TABLE PRE_REQUISITO (
    NOME_DICIPLINA VARCHAR(50) NOT NULL,
    NOME_PRE_REQUISITO VARCHAR(50) NOT NULL,
    SERIAL_SEQ INTEGER NOT NULL,

    FOREIGN KEY (NOME_DICIPLINA) REFERENCES DICIPLINA (NOME),
    FOREIGN KEY (NOME_PRE_REQUISITO) REFERENCES DICIPLINA (NOME),
    PRIMARY KEY (NOME_DICIPLINA)
);



CREATE TABLE INSCRICAO_TURMA (
    ID_INSCRICAO INTEGER NOT NULL,
    NOME_CURSO VARCHAR(50) NOT NULL,
    NOME_DICIPLINA VARCHAR(50) NOT NULL,
    SEMESTRE_ANO INTEGER NOT NULL,
    NOTA FLOAT NOT NULL,

    FOREIGN KEY (ID_INSCRICAO) REFERENCES INSCRICAO (ID),
    FOREIGN KEY (NOME_CURSO) REFERENCES CURSO (NOME),
    FOREIGN KEY (NOME_DICIPLINA) REFERENCES DICIPLINA (NOME),
    FOREIGN KEY (SEMESTRE_ANO) REFERENCES TURMA (SEMESTRE_ANO),
    PRIMARY KEY (ID_INSCRICAO, SEMESTRE_ANO)
);

CREATE TABLE PROFESSOR_LECIONA_TURMA (
    ID_PROFESSOR INTEGER NOT NULL,
    NOME_CURSO VARCHAR(50) NOT NULL,
    NOME_DICIPLINA VARCHAR(50) NOT NULL,
    SEMESTRE_ANO INTEGER NOT NULL,

    FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSOR (ID_PESSOA),
    FOREIGN KEY (NOME_CURSO) REFERENCES CURSO (NOME),
    FOREIGN KEY (NOME_DICIPLINA) REFERENCES DICIPLINA (NOME),
    FOREIGN KEY (SEMESTRE_ANO) REFERENCES TURMA (SEMESTRE_ANO),
    PRIMARY KEY (ID_PROFESSOR, SEMESTRE_ANO)
);

