DROP TABLE IF EXISTS CLIENTE_DVD;
DROP TABLE IF EXISTS FILME_DVD;
DROP TABLE IF EXISTS FILME_GENERO;
DROP TABLE IF EXISTS FILME_ATOR;

DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS DVD;
DROP TABLE IF EXISTS GENERO;
DROP TABLE IF EXISTS ATOR;
DROP TABLE IF EXISTS FILME;

CREATE TABLE FILME (
    ID INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL
);

CREATE TABLE ATOR (
    NOME_REAL CHAR(60) NOT NULL PRIMARY KEY
);

CREATE TABLE GENERO (
    DESCRIÇÃO CHAR(30) NOT NULL PRIMARY KEY
);

CREATE TABLE DVD (
    ID INTEGER NOT NULL PRIMARY KEY
);

CREATE TABLE CLIENTE (
    NUM INTEGER NOT NULL PRIMARY KEY,
    NOME CHAR(60) NOT NULL,
    SOBRENOME CHAR(60) NOT NULL,
    TELEFONE CHAR(20) NOT NULL,
    ENDEREÇO CHAR(60) NOT NULL
);

/*-----------RELAÇÕES---------------*/

CREATE TABLE FILME_ATOR (
    ID_FILME INTEGER NOT NULL,
    ATOR CHAR(60) NOT NULL,

    PRIMARY KEY (ID_FILME, ATOR),
    FOREIGN KEY (ID_FILME) REFERENCES FILME(ID),
    FOREIGN KEY (ATOR) REFERENCES ATOR(NOME_REAL)
);

CREATE TABLE FILME_GENERO (
    ID_FILME INTEGER NOT NULL,
    GENERO CHAR(30) NOT NULL,

    PRIMARY KEY (ID_FILME),
    FOREIGN KEY (ID_FILME) REFERENCES FILME(ID),
    FOREIGN KEY (GENERO) REFERENCES GENERO(DESCRIÇÃO)
);

CREATE TABLE FILME_DVD (
    ID_FILME INTEGER NOT NULL,
    ID_DVD INTEGER NOT NULL,

    PRIMARY KEY (ID_DVD),
    FOREIGN KEY (ID_FILME) REFERENCES FILME(ID),
    FOREIGN KEY (ID_DVD) REFERENCES DVD(ID)
);

CREATE TABLE CLIENTE_DVD (
    ID_CLIENTE INTEGER,
    ID_DVD INTEGER,
    DATA_DEVOLUÇÃO DATE NOT NULL,
    DATA_EMPRESTIMO DATE NOT NULL,
    VALOR_PAGO FLOAT NOT NULL,
    VALOR_A_PAGAR FLOAT NOT NULL,

    PRIMARY KEY (ID_DVD),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(NUM),
    FOREIGN KEY (ID_DVD) REFERENCES DVD(ID)
);

