DROP TABLE IF EXISTS FUNCIONARIO_TEM_CATEGORIA;
DROP TABLE IF EXISTS REPARO_NO_VEICULO_DO_CLIENTE;
DROP TABLE IF EXISTS REPARO_TEM_PEÇA;
DROP TABLE IF EXISTS FUNCIONARIO_FAZ_REPARO;
DROP TABLE IF EXISTS CLIENTE_TEM_VEICULO;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS VEICULO;
DROP TABLE IF EXISTS REPARO;
DROP TABLE IF EXISTS PEÇA;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS CATEGORIA;

CREATE TABLE CLIENTE (
    ID INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL
);

CREATE TABLE VEICULO (
    PLACA VARCHAR(7) NOT NULL PRIMARY KEY
);

CREATE TABLE CATEGORIA (
    NOME VARCHAR(50) NOT NULL PRIMARY KEY,
    CUSTO FLOAT NOT NULL
);

CREATE TABLE FUNCIONARIO (
    ID INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL
);

CREATE TABLE REPARO (
    ID INTEGER NOT NULL PRIMARY KEY,
    CUSTO FLOAT NOT NULL,
    DATA DATE NOT NULL
);

CREATE TABLE PEÇA (
    CODIGO INTEGER NOT NULL PRIMARY KEY,
    DESIGNAÇÃO VARCHAR(50) NOT NULL,
    CUSTO FLOAT NOT NULL,
    QUANTIDADE INTEGER NOT NULL
);

CREATE TABLE CLIENTE_TEM_VEICULO (
    ID_CLIENTE INTEGER NOT NULL,
    ID_VEICULO VARCHAR(7) NOT NULL,

    PRIMARY KEY (ID_CLIENTE, ID_VEICULO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID),
    FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO (PLACA)
);

CREATE TABLE FUNCIONARIO_FAZ_REPARO (
    ID_FUNCIONARIO INTEGER NOT NULL,
    ID_REPARO INTEGER NOT NULL,
    TEMPO_REPARO INTEGER NOT NULL,
    CUSTO_MAO_OBRA FLOAT NOT NULL,

    PRIMARY KEY (ID_FUNCIONARIO, ID_REPARO),
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO (ID),
    FOREIGN KEY (ID_REPARO) REFERENCES REPARO (ID)
);

CREATE TABLE REPARO_TEM_PEÇA (
    ID_REPARO INTEGER NOT NULL,
    CODIGO INTEGER NOT NULL,
    CUSTO FLOAT NOT NULL,

    PRIMARY KEY (ID_REPARO, CODIGO),
    FOREIGN KEY (ID_REPARO) REFERENCES REPARO (ID),
    FOREIGN KEY (CODIGO) REFERENCES PEÇA (CODIGO)
);

CREATE TABLE REPARO_NO_VEICULO_DO_CLIENTE (
    ID_REPARO INTEGER NOT NULL,
    ID_VEICULO VARCHAR(7) NOT NULL,
    ID_CLIENTE INTEGER NOT NULL,

    PRIMARY KEY (ID_REPARO),
    FOREIGN KEY (ID_REPARO) REFERENCES REPARO (ID),
    FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO (PLACA),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID)
);

CREATE TABLE FUNCIONARIO_TEM_CATEGORIA (
    ID_FUNCIONARIO INTEGER NOT NULL,
    NOME_CATEGORIA VARCHAR(50) NOT NULL,

    PRIMARY KEY (ID_FUNCIONARIO),
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO (ID),
    FOREIGN KEY (NOME_CATEGORIA) REFERENCES CATEGORIA (NOME)
);